-- Seed all 14 experiences from experiences.ts
insert into public.experiences (slug, name, tagline, description, schedule, time, package_includes, activities, cover_image_url, images, category, is_featured, is_active, price, deposit_amount, package_tiers, sort_order, whatsapp_message) values

('camping', 'The Camping Experience', '2 nights under the stars',
'Escape the city and spend two unforgettable nights under the stars at Hidden Paradise. Enjoy a full weekend of outdoor adventure, delicious meals, and great company surrounded by nature on the Akuse Road.',
'Weekends', 'Friday – Sunday',
ARRAY['Tent accommodation','Food & Water (Breakfast, Lunch, Dinner)','Washroom facilities','Snacks on arrival','Goody bag (T-shirt & Plant)'],
ARRAY['Boat cruise','Bonfire','Volleyball','Table tennis','Video games','Hiking','Swimming','Movie night','Soccer','Archery','Board games','Music & Good vibes'],
'/images/venue/campground-night.jpeg',
ARRAY['/images/venue/campground-day.jpeg','/images/venue/campground-night.jpeg','/images/venue/campground-moonrise.jpeg','/images/experiences/camping-2nights.jpeg'],
'recurring', true, true, 400, 200, null, 0,
'Hi, I''m interested in the The Camping Experience at Hidden Paradise'),

('party-in-the-woods', 'Party In The Woods', 'Friday nights, reimagined',
'Kick off the weekend every Friday with an unforgettable night in the woods. Dive into the pool, gather around the bonfire for storytelling, play games, and enjoy a full meal with drinks -- all surrounded by good music and great energy.',
'Every Friday', '7:00 PM – 5:00 AM',
ARRAY['Pool party','Bonfire (storytelling)','Fun games','Food & Drinks (Starter & Main dish)'],
ARRAY['Good music (DJ & Karaoke)','Positive vibes','Networking'],
'/images/venue/pool-party.jpeg',
ARRAY['/images/venue/pool-party.jpeg','/images/venue/pool-night.jpeg','/images/experiences/party-woods-2.jpeg'],
'recurring', true, true, 150, 75,
'[{"id":"explorer","name":"The Explorer","price":150,"deposit":75,"description":"Pool Access · All Games · 1 Water · 1 Cocktail"},{"id":"vip","name":"The Enthusiast (VIP)","price":350,"deposit":175,"description":"Priority Entry · Full BBQ Buffet · 2 Waters · 1 Premium Cocktail · Reserved Seating"},{"id":"tribe","name":"The Tribe Bundle (Group of 5)","price":1600,"deposit":800,"description":"VIP Table · Full BBQ for 5 · 2 Buckets of Beer · 1 Sparkling Wine · Dedicated Server"}]'::jsonb,
1, 'Hi, I''m interested in the Party In The Woods at Hidden Paradise'),

('saturday-bbq', 'Saturday BBQ', 'Meat, music, and moonlight',
'Every Saturday evening at Hidden Paradise is a feast. Indulge in all types of grilled meats served with fried rice, yam chips, banku, and abolo. Sip on free local drinks and cocktail shots while networking under the stars.',
'Every Saturday', '7:30 PM – Midnight',
ARRAY['All types of meat to munch on (Fried rice, Yam chips, Banku, Abolo)','Free local drinks','Cocktail shots available'],
ARRAY['Networking & good vibes','Fun games'],
'/images/experiences/saturday-bbq.jpeg',
ARRAY['/images/experiences/saturday-bbq.jpeg'],
'recurring', true, true, 200, 100, null, 2,
'Hi, I''m interested in the Saturday BBQ at Hidden Paradise'),

('game-night', 'Game Night', 'Play hard, laugh harder',
'Every Thursday is Game Night at Hidden Paradise. From classic board games like Ludo and Oware to pool party games, video games, and snooker -- there is something for everyone. Gather around the bonfire, play truth or dare, and you might even win a prize.',
'Every Thursday', '8:00 PM – 2:00 AM',
ARRAY['Snooker','Ludo','Oware','Jenga','Table tennis','Pool party games','Video games','Cards','Truth or dare','Win a prize','Bonfire'],
ARRAY['Snooker','Ludo','Oware','Jenga','Table tennis','Pool party games','Video games','Cards','Truth or dare','Bonfire'],
'/images/experiences/game-night.jpeg',
ARRAY['/images/experiences/game-night.jpeg'],
'recurring', true, true, 100, 50, null, 3,
'Hi, I''m interested in the Game Night at Hidden Paradise'),

('movie-night', 'Friday Movie Night', 'Cinema under the stars',
'Enjoy free entry to Friday Movie Night at Hidden Paradise. Catch the first showing from 7 to 9 PM or the late showing from 10 PM to 1 AM. Popcorn, games, networking, and food & drinks are all available to make your night complete.',
'Every Friday', '7:00 PM – 1:00 AM',
ARRAY['Free entry','Games','Popcorn','Networking'],
ARRAY['First showing 7:00 PM – 9:00 PM','Second showing 10:00 PM – 1:00 AM','Food & drinks available'],
'/images/experiences/movie-night.jpeg',
ARRAY['/images/experiences/movie-night.jpeg'],
'recurring', false, true, null, null, null, 4,
'Hi, I''m interested in the Friday Movie Night at Hidden Paradise'),

('picnic-packages', 'Picnic Packages', 'Your perfect outdoor escape',
'Choose from our Standard Picnic (serves 2 guests) or Family Picnic (serves 3-8 guests). Each package includes a food basket, umbrella, board games, picnic blanket, cutlery, pillows, cooler with ice, bluetooth speaker, and power bank.',
'Available daily', '6 hours duration',
ARRAY['Picnic basket with food','Umbrella','Board games','Picnic blanket','Cutlery and plates','Pillows','Cooler with ice','Bluetooth speaker','Power bank'],
ARRAY['Relaxation','Board games','Photography'],
'/images/experiences/picnic-packages.jpeg',
ARRAY['/images/experiences/picnic-packages.jpeg'],
'recurring', true, true, 150, 75, null, 5,
'Hi, I''m interested in the Picnic Packages at Hidden Paradise'),

('krobo-mountain-hike', 'Krobo Mountain Hiking Tour', 'Conquer the Krobo Mountain',
'Take on the Krobo Mountain with a guided hiking tour. The adventure includes snacks on the trail, a hearty lunch back at Hidden Paradise, and time to unwind with board games, swimming, and soccer. You will also take home a goody bag.',
'Saturdays', '9:00 AM – 5:00 PM',
ARRAY['Hike the Krobo Mountain','Snacks on the hike','Lunch in Hidden Paradise','Goody bag','Shower & washroom facilities'],
ARRAY['Board games','Swimming','Soccer'],
'/images/experiences/krobo-hike.jpeg',
ARRAY['/images/experiences/krobo-hike.jpeg'],
'tour', true, true, 200, 100, null, 6,
'Hi, I''m interested in the Krobo Mountain Hiking Tour at Hidden Paradise'),

('yogaga-mountain-hike', 'Mountain Yogaga Hike', 'Explore the Yogaga trail',
'Hike the scenic Yogaga Mountain and return to Hidden Paradise for a well-deserved lunch. The full-day package includes snacks on the trail, shower and washroom facilities, and a goody bag.',
'Saturdays', '9:00 AM – 5:00 PM',
ARRAY['Hike the Yogaga Mountain','Snacks on the hike','Lunch in Hidden Paradise','Shower and washroom facilities','Goody bag'],
ARRAY['Board games','Swimming','Soccer'],
'/images/experiences/yogaga-hike.jpeg',
ARRAY['/images/experiences/yogaga-hike.jpeg'],
'tour', false, true, 200, 100, null, 7,
'Hi, I''m interested in the Mountain Yogaga Hike at Hidden Paradise'),

('shai-hills-tour', 'Hidden Paradise & Shai Hills Reserve Experience', 'Nature, history, and adventure',
'A full-day adventure combining the Shai Hills Reserve with Hidden Paradise. Enjoy transportation, a professional tour guide, hiking at the reserve, a boat ride on Kpong Dam, swimming pool access, and fun games -- with breakfast and lunch included.',
'Weekends', '6:00 AM – 4:00 PM',
ARRAY['Transportation','Tour charges','Professional tour guide','Hiking at Shai Hills Reserve','Breakfast & Lunch','Boat ride (Kpong Dam)','Swimming pool access','Fun games'],
ARRAY['Hiking','Boat ride','Swimming','Games'],
'/images/experiences/shai-hills.jpeg',
ARRAY['/images/experiences/shai-hills.jpeg'],
'tour', false, true, 300, 150, null, 8,
'Hi, I''m interested in the Hidden Paradise & Shai Hills Reserve Experience at Hidden Paradise'),

('eastern-tour', 'Eastern Tour', 'Discover the Eastern Region',
'Explore the best of Ghana''s Eastern Region in one packed day. Visit the Volta Lake for a boat cruise, cross the iconic Adome Bridge, tour the Akwamu Museum, hike at Shai Hills Reserve, and finish with lunch at Hidden Paradise.',
'Weekends', '9:00 AM – 5:00 PM',
ARRAY['Transportation','Tour charges','Professional tour guide','Snacks on the bus','Volta Lake Boat Cruise','Adome Bridge visit','Akwamu Museum visit','Shai Hills Reserve','Bridge View visit','Networking & good vibes','Fun games','Lunch in Hidden Paradise','Photoshoot'],
ARRAY['Volta Lake Boat Cruise','Adome Bridge visit','Akwamu Museum visit','Shai Hills Reserve','Bridge View visit','Fun games','Lunch in Hidden Paradise','Photoshoot'],
'/images/experiences/eastern-tour.jpeg',
ARRAY['/images/experiences/eastern-tour.jpeg'],
'tour', false, true, 300, 150, null, 9,
'Hi, I''m interested in the Eastern Tour at Hidden Paradise'),

('sunset-gardens', 'Sunset Gardens', 'Nature''s beauty, curated',
'Beautiful landscaped gardens offering the sale of flowers, flower pots, garden arts, and landscape designs. A tranquil space for photography, shopping, and simply enjoying nature at Hidden Paradise.',
'Open daily', 'All day',
ARRAY['Sale of flowers','Sale of flower pots','Sale of garden arts','Landscape designs'],
ARRAY['Garden tours','Shopping','Photography'],
'/images/venue/gardens.jpeg',
ARRAY['/images/venue/gardens.jpeg','/images/experiences/sunset-gardens.jpeg'],
'special', false, true, null, null, null, 10,
'Hi, I''m interested in the Sunset Gardens at Hidden Paradise'),

('farm', 'Hidden Paradise Farm', 'From soil to table',
'Visit the Hidden Paradise Farm for a hands-on experience with fresh produce. Take a farm tour, buy spices, herbs, and fresh vegetables, enjoy a farm-to-table meal, or enrol in a learn-to-grow-food course.',
'Open daily', 'All day',
ARRAY['Farm tour','Sale of spices & herbs','Sale of fresh vegetables','Farm to table experience','Learn to grow food course'],
ARRAY['Farming','Learning','Cooking'],
'/images/experiences/farm.jpeg',
ARRAY['/images/experiences/farm.jpeg'],
'special', false, true, 80, 40, null, 11,
'Hi, I''m interested in the Hidden Paradise Farm at Hidden Paradise'),

('art-show', 'Art Show', 'Creativity meets community',
'Hidden Paradise''s Art Show is a free-entry celebration of creativity. Browse exhibitions, join sip & paint sessions, watch an art auction, try bead making and pottery classes, and enjoy live music, face painting, and fun games throughout the day.',
'Special events', '10:00 AM – 10:00 PM',
ARRAY['Free entry','Art exhibitions','Sip & paint','DJ & music','Face painting','Photography','Art auction','Art competition','Bead making','Pottery classes','Fun games','Networking','Table tennis','Soccer'],
ARRAY['Art exhibitions','Sip & paint','DJ & music','Face painting','Photography','Art auction','Bead making','Pottery classes','Fun games','Networking'],
'/images/experiences/art-show.jpeg',
ARRAY['/images/experiences/art-show.jpeg'],
'special', false, true, null, null, null, 12,
'Hi, I''m interested in the Art Show at Hidden Paradise'),

('family-fun-day', 'Family Fun Day', 'Fun for every age',
'Bring the whole family to Hidden Paradise for a day packed with activities for all ages. Enjoy free entry with horse riding, bouncy castle, swimming, video games, face painting, arts & crafts, Lego, table tennis, soccer, and more.',
'Special events', 'All day',
ARRAY['Free entry','Horse riding','Bouncy castle','Swimming','Video games','Face painting','Table tennis','Soccer','Arts & crafts','Lego & a few games'],
ARRAY['Horse riding','Bouncy castle','Swimming','Video games','Face painting','Table tennis','Soccer','Arts & crafts'],
'/images/experiences/family-fun-day.jpeg',
ARRAY['/images/experiences/family-fun-day.jpeg'],
'special', false, true, null, null, null, 13,
'Hi, I''m interested in the Family Fun Day at Hidden Paradise'),

('garden-fair', 'Garden Fair', 'Bloom, browse, and enjoy',
'A free-entry garden event featuring plant and flower exhibitions, garden art and furniture displays, live music, networking, and photoshoots. Browse and buy flowers, flower pots, and garden accessories.',
'Special events', '9:00 AM – 4:00 PM',
ARRAY['Free entry','Plant & flower exhibition','Garden art & furniture exhibition','Networking','Music & DJs','Photoshoot','Sale of flowers/flower pots'],
ARRAY['Plant & flower exhibition','Garden art & furniture exhibition','Networking','Music & DJs','Photoshoot'],
'/images/experiences/garden-fair.jpeg',
ARRAY['/images/experiences/garden-fair.jpeg'],
'special', false, true, null, null, null, 14,
'Hi, I''m interested in the Garden Fair at Hidden Paradise'),

('night-market', 'Night Market', 'Shop, vibe, and unwind',
'Hidden Paradise''s Night Market is a free-entry evening event with music, a bonfire, movies in the park, arts & crafts sales, flea market finds, and fresh farm produce. A perfect way to spend the night with great vibes and good company.',
'Special events', '7:00 PM – 12:00 AM',
ARRAY['Free entry','Music & DJ','Good vibes','Networking','Movies in the park','Bonfire','Arts & crafts sale','Flea market sales','Fresh farm produce sale'],
ARRAY['Music & DJ','Networking','Movies in the park','Bonfire','Arts & crafts sale','Flea market sales','Fresh farm produce sale'],
'/images/experiences/night-market.jpeg',
ARRAY['/images/experiences/night-market.jpeg'],
'special', false, true, null, null, null, 15,
'Hi, I''m interested in the Night Market at Hidden Paradise');
